// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RecipeManager.ApiService.Data;

#nullable disable

namespace RecipeManager.ApiService.Migrations.IngredientListDb
{
    [DbContext(typeof(IngredientListDbContext))]
    [Migration("20260513212935_AddListShareTokenAccessLevel")]
    partial class AddListShareTokenAccessLevel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RecipeManager.ApiService.Data.Ingredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IngredientListId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsChecked")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Quantity")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("IngredientListId");

                    b.HasIndex("IngredientListId", "IsChecked");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("RecipeManager.ApiService.Data.IngredientList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("OwnerId");

                    b.ToTable("IngredientLists");
                });

            modelBuilder.Entity("RecipeManager.ApiService.Data.ListShareToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessLevel")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IngredientListId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Token")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("IngredientListId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("ListShareTokens");
                });

            modelBuilder.Entity("RecipeManager.ApiService.Data.ListSharing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessLevel")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IngredientListId")
                        .HasColumnType("uuid");

                    b.Property<string>("ShareType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("SharedWithUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IngredientListId");

                    b.HasIndex("SharedWithUserId");

                    b.HasIndex("IngredientListId", "SharedWithUserId")
                        .IsUnique();

                    b.ToTable("ListSharings");
                });

            modelBuilder.Entity("RecipeManager.ApiService.Data.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CookTimeMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Ingredients")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int?>("PrepTimeMinutes")
                        .HasColumnType("integer");

                    b.Property<int?>("Servings")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Recipes", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("RecipeManager.ApiService.Data.RecipeIngredientList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("AddedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IngredientListId")
                        .HasColumnType("uuid");

                    b.Property<int>("RecipeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IngredientListId");

                    b.HasIndex("RecipeId");

                    b.HasIndex("IngredientListId", "RecipeId")
                        .IsUnique();

                    b.ToTable("RecipeIngredientLists");
                });

            modelBuilder.Entity("RecipeManager.ApiService.Data.Ingredient", b =>
                {
                    b.HasOne("RecipeManager.ApiService.Data.IngredientList", "IngredientList")
                        .WithMany("Ingredients")
                        .HasForeignKey("IngredientListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IngredientList");
                });

            modelBuilder.Entity("RecipeManager.ApiService.Data.ListShareToken", b =>
                {
                    b.HasOne("RecipeManager.ApiService.Data.IngredientList", "IngredientList")
                        .WithMany("ShareTokens")
                        .HasForeignKey("IngredientListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IngredientList");
                });

            modelBuilder.Entity("RecipeManager.ApiService.Data.ListSharing", b =>
                {
                    b.HasOne("RecipeManager.ApiService.Data.IngredientList", "IngredientList")
                        .WithMany("Sharings")
                        .HasForeignKey("IngredientListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IngredientList");
                });

            modelBuilder.Entity("RecipeManager.ApiService.Data.RecipeIngredientList", b =>
                {
                    b.HasOne("RecipeManager.ApiService.Data.IngredientList", "IngredientList")
                        .WithMany("RecipeLinks")
                        .HasForeignKey("IngredientListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecipeManager.ApiService.Data.Recipe", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IngredientList");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("RecipeManager.ApiService.Data.IngredientList", b =>
                {
                    b.Navigation("Ingredients");

                    b.Navigation("RecipeLinks");

                    b.Navigation("ShareTokens");

                    b.Navigation("Sharings");
                });
#pragma warning restore 612, 618
        }
    }
}
